# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('campaigns', '0005_auto_20170402_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='Input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('display_type', models.CharField(choices=[('text', 'text'), ('file', 'file'), ('select', 'select'), ('multi-select', 'multi-select'), ('checkbox', 'checkbox')], max_length=100)),
                ('predefined_values', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Survey',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_message', models.CharField(max_length=200)),
                ('header_image', models.FileField(upload_to=b'')),
                ('ad', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='campaigns.Ad')),
            ],
        ),
        migrations.AddField(
            model_name='input',
            name='survey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forman.Survey'),
        ),
    ]
