# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 15:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forman', '0003_auto_20170503_1110'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sumission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('columns', models.TextField()),
                ('values', models.TextField()),
                ('survey', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forman.Survey')),
            ],
        ),
    ]
