# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-02 14:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forman', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='survey',
            name='footer_image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='survey',
            name='footer_message',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='survey',
            name='header_image',
            field=models.FileField(blank=True, null=True, upload_to=b''),
        ),
    ]
