# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-05-03 15:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forman', '0004_sumission'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sumission',
            new_name='Submission',
        ),
    ]
